### ISSUE TITLE
world edit fails to connect blocks

### ISSUE THREAD

**Issue by Bixloof** [StarLegacy/Issue-Tracker#102]
World edit will not keep the position of a previous block if you covert it to a diff block. IE if i turn a stone brick stair facing north into quarts it will face west (or whatever direction the normal stairs direction is for w/e

**Comment by Bixloof** [comment]
also same with iron bars

**Comment by MicleBrick** [comment]
Not our problem

**Comment by Bixloof** [comment]
yes your problem. thats a SERVER issue kek
