### ISSUE TITLE
DNs r borked lol

### ISSUE THREAD

**Issue by Bixloof** [StarLegacy/Issue-Tracker#105]
Epic and I had a DN fight in creative and i was able to get his shield to red in abt 30 while he killed my nose is abt 25 seconds. Morale of the story DNs can die within 3 mins of fighting and that is wayyyyy to shot for THE BIGGEST SHIP IN THE GAME

**Comment by MicleBrick** [comment]
Resubmit with specific bugs and a proper title and description
