### ISSUE TITLE
Update Issue - Machines Exploding

### ISSUE THREAD

**Issue by LeMaire69** [StarLegacy/Issue-Tracker#147]
I looked in my autocrafter and it exploded. 

Also pipes aren't working again.

**Comment by zelrond** [comment]
Pipes. Still not working. Confirmed

**Comment by MicleBrick** [comment]
duplicate of https://github.com/StarLegacy/Issue-Tracker/issues/186 and https://github.com/StarLegacy/Issue-Tracker/issues/181
