### ISSUE TITLE
Special minerals are all mixed up in terrain

### ISSUE THREAD

**Issue by zelrond** [StarLegacy/Issue-Tracker#172]
Terram has now lots of uranium instead of titanium for example. Ive seen blocks of copper turned into cheterite ore, other stuff turned into aluminum blocks... most is ok (like titanium is still the most usual mineral in terram) but theres a lot of the other ones now too, like entire blocks of them, not only ores.

**Comment by CodingIsAHabit** [comment]
Reported to be fixed. Please re-open if you see it happen again.
