### ISSUE TITLE
Redstone lamp thruster and landing gear

### ISSUE THREAD

**Issue by zelrond** [StarLegacy/Issue-Tracker#173]
These two are not working, i believe its related to the redstone block somehow since both of them share some functionality and have it as part of the multiblock. 

- Landingear turns into lapis and leaves the pistons abandoned. 
- Redstone lamp thruster isnt providing trust at all, it doesn't sum to final speed at least, i dont know if they provide accel.

TEST: Landingear is easy to test. For redstone lamp thruster just try to cruise with a ONLY redstonelamp thruster ship. Cruising is not possible is the system error.

**Comment by MicleBrick** [comment]
Open a separate issue for landing gears

**Comment by MicleBrick** [comment]
(redstone lamp issue solved)
