### ISSUE TITLE
[BUG] Enabling / disabling ship lock undetects ship 

### ISSUE THREAD

**Issue by Gutin1** [StarLegacy/Issue-Tracker#188]
**Describe the bug**
Enabling or disabling a starship's lock undetects it, requiring it to be redetected. 

**To Reproduce**
Detect ship
Enable / disable lock
Ship needs to be redetected 

![image](https://user-images.githubusercontent.com/57606752/93290073-874f3100-f7a5-11ea-99d8-88ca53cf0246.png)

**Comment by Maxbrick** [comment]
Just tried it now, it works just fine.
![2020-11-01_10 19 07](https://user-images.githubusercontent.com/71112739/97806872-d1905280-1c2b-11eb-8aee-14ca2cb2d41d.png)
