### ISSUE TITLE
Bug: Ship printers dont work with money printing

### ISSUE THREAD

**Issue by Bixloof** [StarLegacy/Issue-Tracker#189]
Money printing does not work when trying to print a ship in survival.
**To Reproduce**
1. Go to Bixlo's base Quod: Gondor
2. Click on the ship printing sign trying to print the red ship
3. Scroll down to nowhere just click the sign
4. See error(no error is just dosent print with money)

**Expected behavior**
It uses money to print the ship
**Screenshots**
no thanks
**System (please complete the following information):**
- OS: [e.g. Windows]
- CPU: [e.g. Intel i5 6th gen]
- RAM: [e.g. 8gb RAM]
- Minecraft Version: [e.g. Minecraft Java Edition 1.16.3]

**Additional context**

**Comment by MicleBrick** [comment]
1. No screenshots included
2. Left click to money print
