### ISSUE TITLE
Massive duping of items [BUG]

### ISSUE THREAD

**Issue by zelrond** [StarLegacy/Issue-Tracker#195]
**Describe the bug**
Another way items are getting duped

**To Reproduce**
1. Craft a power module, i did specifically the shock absorving one
2. Instead of clicking, do shift click
3. Aluminum and glass panes get duped in massive quantities instantly. I got more than 3 dupes, since it lagged so much i just deleted it all. I left a couple stacks of the aluminum to show of proof. They are at 1982 136 1453 in terram

**Comment by hafarooki** [comment]
fixed
