### ISSUE TITLE
[BUG] Heavy Lasers are not firing

### ISSUE THREAD

**Issue by Peter-Crawley** [StarLegacy/Issue-Tracker#196]
**Describe the bug**
Heavy Lasers are not firing

**To Reproduce**
1. Fire a heavy laser

**Expected behavior**
It fires a Heavy Laser

**System (please complete the following information):**
- OS: Arch Linux
- CPU: AMD Ryzen 3 2200g
- RAM: 8GB (6GB Available)
- Minecraft Version: Minecraft Java 1.16.3 w/ Fabric Loader

**Comment by MicleBrick** [comment]
They work fine, but heavy lasers and torpedos now require you to be aiming at a block to shoot.
