### ISSUE TITLE
Gas Multiblock Not Working

### ISSUE THREAD

**Issue by WatchmanPhileo** [StarLegacy/Issue-Tracker#200]
Gas collectors at y251 are not working. Sign will activate but will not collect gas.  

Can be tested and replicated at Atlantis gas rig above main city.

**Comment by hafarooki** [comment]
Multiblock is fine. As for collection, this issue covers this in more detail so I'll close this one in favor of that: https://github.com/StarLegacy/Issue-Tracker/issues/238
