### ISSUE TITLE
[BUG] Idk if its a feature but all ships are broken as now .8shields have an 8 radius instead of a 10

### ISSUE THREAD

**Issue by SciathGH** [StarLegacy/Issue-Tracker#206]
**Describe the bug**

Before in 1.12 the .8shields and every shield were 2 more blocks then what was written in wiki however this is not the case in 1.16 nearly every ship
**To Reproduce**

**Expected behavior**

**Screenshots**

**System (please complete the following information):**
- OS: [e.g. Windows]
- CPU: [e.g. Intel i5 6th gen]
- RAM: [e.g. 8gb RAM]
- Minecraft Version: [e.g. Minecraft Java Edition 1.16.3]

**Additional context**

This breaks Every ship built with that feature, which is alot of ships from alot of nations please fix/revert this

**Comment by MicleBrick** [comment]
Format the issue properly.
