### ISSUE TITLE
[BUG] Heavy turrets shots are far too fast

### ISSUE THREAD

**Issue by SciathGH** [StarLegacy/Issue-Tracker#208]
**Describe the bug**

a full barrage hits a frigate at max speed every time 
**To Reproduce**

**Expected behavior**

**Screenshots**

**System (please complete the following information):**
- OS: [e.g. Windows]
- CPU: [e.g. Intel i5 6th gen]
- RAM: [e.g. 8gb RAM]
- Minecraft Version: [e.g. Minecraft Java Edition 1.16.3]

**Additional context**

**Comment by MicleBrick** [comment]
missing steps to reproduce, missing expected behavior, missing screenshots
