### ISSUE TITLE
[BUG] Heavy turrets shots are far too fast

### ISSUE THREAD

**Issue by SciathGH** [StarLegacy/Issue-Tracker#211]
**Describe the bug**

Yesterday when I was fighting A batlecruiser in a frigate it was near impossible for me to get into firing distance of him without immediately getting shredded by the heavy turrets.
**To Reproduce**

Fly a frigate and try fight a battlecruiser in it.
**Expected behavior**

You should see that its far harder to fight then in 1.12, which is not necicarilly a bad thing but its still far too fast
**Screenshots**

what screenshots could I send?
**System (please complete the following information):**
- OS: [e.g. Windows] Windows
- CPU: [e.g. Intel i5 6th gen] Intel i5
- RAM: [e.g. 8gb RAM] 8gb
- Minecraft Version: [e.g. Minecraft Java Edition 1.16.3] java 1.16.3

**Additional context**

**Comment by hafarooki** [comment]
this is no longer relevant with the upcoming svs update
