### ISSUE TITLE
[BUG] Ship remains piloted after the pilot is killed

### ISSUE THREAD

**Issue by Peter-Crawley** [StarLegacy/Issue-Tracker#217]
**Describe the bug**

Ship remains piloted after the pilot is killed

**To Reproduce**

Have player pilot a ship, kill pilot.

**Expected behavior**

The ship becomes unpiloted.

**Screenshots**

I don't have any screenshots.

**System (please complete the following information):**
- OS: Arch Linux
- CPU: Ryzen 3 2200g
- RAM: 8GB, 6GB available
- Minecraft Version: Minecraft Java Edition 1.16.3 w/ Fabric Loader and 8 mods.
- Mod List:
AppleSkin (1.0.11)
Fabric API (0.20.2+build.402-1.16)
Hwyla (1.9.22)
Inventory Profiles (0.4.2)
OptiFabric (1.6.4)
OptiFine (1.16.3 HD U G3)
StarMod (0.2.0-Dev)
Xaero's Minimap (20.22.0)

**Comment by hafarooki** [comment]
screenshots required

**Comment by Astralchroma** [comment]
I don't have any to give, and it will take ages to get them.
