### ISSUE TITLE
Creative FREEZES when someone uses the COMPASS [BUG]

### ISSUE THREAD

**Issue by zelrond** [StarLegacy/Issue-Tracker#220]
**Describe the bug**
When you use the compass to go trough things or on top of them (be it right or left click), creative starts to die. First commands stop working, but you still can move around, many seconds later it dies and kicks you out.

**To Reproduce**
Grab a compass in your hand.
Aim at a minecraft block
Press left or right click
Server slowly and agonizingly dies.

**Expected behavior**
Compass clicks should make you go trough stuff or on top of blocks. Its used to move around.

**Screenshots**
N/A

**System (please complete the following information):**
Windows. Minecraft version 1.16.3

**Additional context**
This is serious, since anyone ill intended (Peter) could maliciously abuse this to freeze the server (Peter) and show off that the update was a mistake. It could be anyone! (Peter)

**Comment by hafarooki** [comment]
Does this still happen?

**Comment by zelrond** [comment]
Nope. Solved!

**Comment by zelrond** [comment]
Fixed!
