### ISSUE TITLE
[BUG] Shipfactories use more blocks than they need for material printing

### ISSUE THREAD

**Issue by ItsAlreadyGold** [StarLegacy/Issue-Tracker#226]
**Describe the bug**

When material printing, putting in more materials than the blueprint asks for will delete certain specific materials. In my experience this happens with smooth stone slabs, but I have heard it can happen with concrete.

**To Reproduce**

Try material printing a ship blueprint that uses top smooth stone slabs, and put more slabs than the blueprint calls for into the shipfactory chest. The shipfactory will correctly print the smooth stone slabs, but it will delete any excess smooth stone slabs in the chest, as if it is printing them when they already exist.

**Expected behavior**

In the provided screenshots, I attempted to material print a blueprint that required only 800 (12.5 stacks) smooth stone slabs. I provided the shipfactory chest with 3456 smooth stone slabs, which is a full double chest (54 stacks). The expected behavior would be for the blueprint to print properly and for the ship factory chest to end up with 2656 smooth stone slabs, or 41.5 stacks.

As shown in the screenshots, however, the shipfactory "uses" the remaining 41.5 stacks of smooth stone slab, deleting them.

**Screenshots**

![2020-10-11_18 14 46](https://user-images.githubusercontent.com/37640079/95691562-eca01180-0bed-11eb-89fd-a7845c97f92e.png)
![2020-10-11_18 15 58](https://user-images.githubusercontent.com/37640079/95691564-ef9b0200-0bed-11eb-8bd9-b72f5df911c1.png)
![2020-10-11_18 16 04](https://user-images.githubusercontent.com/37640079/95691566-f0cc2f00-0bed-11eb-9e53-68622f14dfb3.png)
![2020-10-11_18 19 04](https://user-images.githubusercontent.com/37640079/95691605-46084080-0bee-11eb-9ad5-7cc78f9626bc.png)

**System (please complete the following information):**

- OS: Windows 10
- RAM: 8 GB RAM
- Minecraft Version: Java 1.16.3

**Additional context**

**Comment by hafarooki** [comment]
This should be fixed next restart. LMK if not.
