### ISSUE TITLE
[BUG] Smooth Quartz doesn't work for ship blocks

### ISSUE THREAD

**Issue by gb915** [StarLegacy/Issue-Tracker#227]
**Describe the bug**
Built my ship out of smooth quartz block, the kind you get from cooking the regular quartz block, controller isn't detecting it.
**To Reproduce**
Build a ship out of smooth quartz and try to fly it

**Expected behavior**
It should be able to fly just fine, smooth quartz isn't naturally occurring

**Screenshots**
This doesn't really help I guess but I can show the ship saying there's smooth quartz in the way when I try to move it
https://cdn.discordapp.com/attachments/346403151202746389/765135887839264798/unknown.png

**System (please complete the following information):**
Java 1.16.3, rest isn't really applicable since it's a server-side error

**Additional context**
Also related, the printer wouldn't place the smooth quartz- it used all the items but it didn't place a single one

**Comment by hafarooki** [comment]
use slabs/double slabs
