### ISSUE TITLE
Idk if this is the place but Boarding is incredibly unbalanced

### ISSUE THREAD

**Issue by SciathGH** [StarLegacy/Issue-Tracker#232]
**Describe the bug**

So basically boarding is without a doubt a fantastic feature but it make fighting in big ships above corvette sized a very bad idea
**To Reproduce**

Fight somone while having another person boarding u
**Expected behavior**

as soon as theyre attached which is easier done then said as u can dodge at shots extremly easily you should very soon notice the fact that You cnanot get rid of them and youre doomed as the at's dont even work at deterring boarders too half the time
**Screenshots**

**System (please complete the following information):**

- OS: [e.g. Windows] windows
- RAM: [e.g. 8gb RAM 8gb ram
- Minecraft Version: [e.g. Minecraft Java Edition 1.16.3] java 1.16.3

**Additional context**

This basically makes big ships the worst idea on the server to use

**Comment by hafarooki** [comment]
1. not specific enough
2. already reported in another issue
