### ISSUE TITLE
Custom Block Dupe Glitch [BUG]

### ISSUE THREAD

**Issue by Oriomium** [StarLegacy/Issue-Tracker#233]
**Describe the bug**
When you place a custom block (i.e. oriomium blocks, copper blocks) in survival, and then break the block, it drops two blocks. You can continue doing this perpetually for an  infinite supply of minerals. NOTE: I have only tested it with oriomium, but I have heard from others that this happens to copper aswell.

**To Reproduce**
To reproduce, go into survival mode with 1 block of your choice (oriomium definitely works) and a power drill. Place the block. Then, break the block. It will drop two blocks.

**Expected behavior**
I expected that it would drop one block, but it dropped two.

**Screenshots**
https://imgur.com/a/6RJKNG4

**System (please complete the following information):**

- OS: Windows 10
- RAM: 8GB RAM
- Minecraft Version: Java Edition 1.16.3

**Additional context**
Unsure if this works with copper, aluminum, titanium, or chetherite. Certain it works for oriomium, and mostly sure it works with copper.

**Comment by hafarooki** [comment]
Does this issue occur with a pickaxe?

**Comment by Mr-CleanCreeper** [comment]
Can confirm this glitch works with all custom blocks. You also seem to be able to break the block with a chainsaw then replace the block and break it with a drill to receive extra items.

**Comment by hafarooki** [comment]
fixed
