### ISSUE TITLE
[BUG] 08i shields/reinforced shields dont detect as multiblocks

### ISSUE THREAD

**Issue by SciathGH** [StarLegacy/Issue-Tracker#234]
**Describe the bug**

they dont turn into a .8i shield after right clicking
**To Reproduce**

right click a .8i multiblock shield with [shield] on first line and name on the second
**Expected behavior**

Wont work
**Screenshots**

![2020-10-15_19 01 08_2](https://user-images.githubusercontent.com/67932943/96168832-3d2eac00-0f19-11eb-843e-fda22d2177a9.png)

**System (please complete the following information):**

- OS: [e.g. Windows] Windows
- RAM: [e.g. 8gb RAM] 8gb
- Minecraft Version: [e.g. Minecraft Java Edition 1.16.3] java 1.16.3
**Additional context**

**Comment by SciathGH** [comment]
turns out kwaz could do it in dutmode

**Comment by SciathGH** [comment]
Ok so an update onto this, it doesnt do it for most shields and many other members of the server are encountering issues with docking tubes power machines and some shields, ive only found issue with .8i shields and 1.2 shields havnt tested the others

**Comment by SciathGH** [comment]
also turq could do it out of dutymode

**Comment by hafarooki** [comment]
cannot reproduce, need reproducable steps.
