### ISSUE TITLE
Gas collectors nonfunctional[BUG]

### ISSUE THREAD

**Issue by Mr-CleanCreeper** [StarLegacy/Issue-Tracker#238]
**Describe the bug**
  
 

 Gas collection multiblock furnaces do not collect gas

**To Reproduce**
 

Build a gas collection multiblock and place prismarine crystal in bottom and empty gas canister in top of furnace

**Expected behavior**

It is expected to slowly fill up the empty bottle with gas and output the full gas canister into a hopper which can be pointed at a chest
**Screenshots**

![2020-10-18_15 59 56](https://user-images.githubusercontent.com/73080390/96385688-22e41080-115b-11eb-80e9-c21de4595a37.png)

**System (please complete the following information):**

- OS: [e.g. Windows]
- RAM: [e.g. 8gb RAM]
- Minecraft Version: [e.g. Minecraft Java Edition 1.16.3]
OS: Windows 10
RAM: 32Gb
Java edition 1.16.3
**Additional context**

**Comment by Maxbrick** [comment]
fixed
