### ISSUE TITLE
Shipdealer in Jadiid still not working [BUG]

### ISSUE THREAD

**Issue by zelrond** [StarLegacy/Issue-Tracker#241]
**Describe the bug**
Same as https://github.com/StarLegacy/Issue-Tracker/issues/177
Shipdealer missing in Jadiid

**To Reproduce**
Be a newbie
Try to buy a ship in Jadiid
No shipdealer

**Expected behavior**
Shipdealer available, ships available for sale

**System (please complete the following information):**
Windows 10

**Additional context**
New player experience is very bad right now, i think instead of a shipdealer, a ferry carrying to a spacestation in the newbie system should be implemented, and on that station a shipdealer sells them. It's MUCH better to have a starter ships cementery in space than to have it in Jadiid. Right now its horrible imo!

**Comment by hafarooki** [comment]
Get an admin (read: Oriomium or Gutin) to do `/npc create "Ship Dealer"`

**Comment by zelrond** [comment]
Gen explained to me, the issue is it despawns all the time. He is loading a new issue about it!

**Comment by zelrond** [comment]
Solved. Ask an ADMIN if the shipdealer dissapears again
