### ISSUE TITLE
Warp plates in spawn don't work [BUG]

### ISSUE THREAD

**Issue by zelrond** [StarLegacy/Issue-Tracker#242]
**Describe the bug**
New players trying to use the warps in Jadiid (to the tutorial, or back to spawn and such) dont work.

**To Reproduce**
Be a new player
Stand on a plate that says will tp you somewhere (the tutorial one for example)
Nothing happens

**Expected behavior**
Should take you to the indicated spot

**System (please complete the following information):**
C'mon... really? Windows 10 MC java 1.16.3

**Additional context**
Part of the bad starter player experience. Also, a ferry to a space station would be a very cool way to give the new players the first glance at space. The station could be near the asteroid belt. And it could even ferry them across all 3 planets of that system like it was in sobrii! Thats a GOOD starter experience imo!

**Comment by Peregri** [comment]
fixed

**Comment by zelrond** [comment]
https://github.com/JorelAli/CommandAPI

Suggestion for re-enabling the @p on the command blocks for non-vanilla commands.
