### ISSUE TITLE
[BUG] Unable to //confirm

### ISSUE THREAD

**Issue by Astralchroma** [StarLegacy/Issue-Tracker#244]
**Describe the bug**

Cant do //confirm with FAWE on big edits.

**To Reproduce**

Do a million block+ world edit and do //confirm, may not work with staff as they prob have perms, idk

**Expected behavior**

It does the world edit

**Screenshots**

![Screenshot from 2020-10-21 21-33-32](https://user-images.githubusercontent.com/49043380/96783500-6ea9ea80-13e5-11eb-8378-402af05d24e8.png)

**System (please complete the following information):**

- OS: Arch Linux
- RAM: 8gb (6gb usable)
- Minecraft Version: Minecraft 1.16.3 w/ Fabric & Optifine

**Additional context**

Doing world edits this big would have been dumb on normal world edit but with FAWE it's fine.

**Comment by hafarooki** [comment]
Report to them, not to us.

**Comment by Astralchroma** [comment]
This is a permission error as it clearly says in the output, you need to give us access to fawe.confirm

**Comment by Astralchroma** [comment]
Even then I can't report it as I dont have access to the server logs, you need to report it to them
