### ISSUE TITLE
[BUG] FAWE likes to spam debug messages

### ISSUE THREAD

**Issue by Astralchroma** [StarLegacy/Issue-Tracker#246]
**Describe the bug**

Debug messsage spam.

**To Reproduce**

Do anything with world edit.

**Expected behavior**

It does not spam my chat

**Screenshots**

![Screenshot from 2020-10-22 21-30-25](https://user-images.githubusercontent.com/49043380/96926913-27d3f780-14ae-11eb-9743-d822730dd315.png)

**System (please complete the following information):**

- OS: Arch Linux
- RAM: 8gb, 6 avalible
- Minecraft Version: 1.16.3 w/ optifine and fabric

**Additional context**

why do you need my system info... clearly a server config issue

**Comment by CodingIsAHabit** [comment]
Issue resolved
