### ISSUE TITLE
[BUG] balancing again, heavy laser individual Charge times is broken

### ISSUE THREAD

**Issue by SciathGH** [StarLegacy/Issue-Tracker#249]
**Describe the bug**

For god sakes if I make a ship fo pure hl's and put them on each side and shoot them all in one arrray of firing You could no doubt decimate every single ship u come across, remove individual charge time and re-add the charge times to be universal.
**To Reproduce**

test combat again! and go and use one of the ships mentioned above
**Expected behavior**

The ship u fire at is gonna die and theres nothing that ship can do but run, and ofc you cant evade the shots either
**Screenshots**

**System (please complete the following information):**

- OS: [e.g. Windows] windows
- RAM: [e.g. 8gb RAM] 8gb
- Minecraft Version: [e.g. Minecraft Java Edition 1.16.3] java 1.16.3

**Additional context**

**Comment by hafarooki** [comment]
Insufficient details, especially for reproducing.
