### ISSUE TITLE
[BUG] all shields take damage at once

### ISSUE THREAD

**Issue by SciathGH** [StarLegacy/Issue-Tracker#251]
**Describe the bug**

look at the video in screenshots
**To Reproduce**

https://youtu.be/T9UKFZrmw0U
**Expected behavior**

https://youtu.be/T9UKFZrmw0U
**Screenshots**

https://youtu.be/T9UKFZrmw0U
**System (please complete the following information):**

- OS: [e.g. Windows] windows
- RAM: [e.g. 8gb RAM] 8gb
- Minecraft Version: [e.g. Minecraft Java Edition 1.16.3] java 1.16.3

**Additional context**

if u dont understand this micle im giving up hope
https://youtu.be/T9UKFZrmw0U

**Comment by Astralchroma** [comment]
using windows? smh

**Comment by SciathGH** [comment]
better then arch linux smh

**Comment by hafarooki** [comment]
Invalid submission
