### ISSUE TITLE
[BUG] Customitem spam command

### ISSUE THREAD

**Issue by SciathGH** [StarLegacy/Issue-Tracker#252]
**Describe the bug**

Peter filled my inventory using /customitem uranium_block 99999 Sciath
**To Reproduce**

https://youtu.be/G90-feZk2eI
**Expected behavior**

https://youtu.be/G90-feZk2eI
**Screenshots**

https://youtu.be/G90-feZk2eI
**System (please complete the following information):**

- OS: [e.g. Windows] windows
- RAM: [e.g. 8gb RAM] 8gb
- Minecraft Version: [e.g. Minecraft Java Edition 1.16.3] java 1.16.3

**Additional context**

https://youtu.be/G90-feZk2eI

**Comment by SciathGH** [comment]
this has been a bug since 1.12.2

**Comment by hafarooki** [comment]
Invalid submission
