### ISSUE TITLE
[BUG] at's barely hit u and u can turn very fast

### ISSUE THREAD

**Issue by SciathGH** [StarLegacy/Issue-Tracker#253]
**Describe the bug**

i think the video is concise enoughhttps://youtu.be/fN-54lDVRdI
**To Reproduce**

https://youtu.be/fN-54lDVRdI
**Expected behavior**

https://youtu.be/fN-54lDVRdI
**Screenshots**

https://youtu.be/fN-54lDVRdI
**System (please complete the following information):**

- OS: [e.g. Windows] windows- RAM: [e.g. 8gb RAM] 8gb
- Minecraft Version: [e.g. Minecraft Java Edition 1.16.3] java 1.16.3

**Additional context**

https://youtu.be/fN-54lDVRdI

**Comment by hafarooki** [comment]
Invalid submission
