### ISSUE TITLE
/jump doesn't work in Space Arena

### ISSUE THREAD

**Issue by silkbeast** [StarLegacy/Issue-Tracker#254]
---
name: Bug Report
about: Create a report to help us improve
title: /jump doesn't work in Space Arena
labels: bug, /jump, Space Arena, SArena
assignees: ''

---

**Describe the bug**
When you do /jump [co-ordinates] in Space Arena, it shows "you do not have access to this command"

**To Reproduce**
get in a ship in Space Arena with a loaded hyperdrive and working navcomputer, and do /jump [co-ordinates]

**Expected behavior**
Jump to hyperspace after a short charging time and then come out at the co-ordinates specified

**Screenshots**
![image](https://user-images.githubusercontent.com/71288604/97107902-e3b94080-16c1-11eb-87fc-dbef36e95375.png)

**System (please complete the following information):**

- OS: Windows
- RAM: 8gb RAM
- Minecraft Version: Minecraft Java Edition 1.16.3

**Comment by hafarooki** [comment]
Should be fixed
