### ISSUE TITLE
Navigation Computer /jump x y not working/does not exist on server currently[BUG]

### ISSUE THREAD

**Issue by WatchmanPhileo** [StarLegacy/Issue-Tracker#256]
HIGH PRIORITY: Currently on the server multiple players have reported that hyperspace/hyper jumping are down. I am not sure if this is a problem with the navigation computer multiblock, hyperdrive multiblocks, or just the general hyperspace dynamic on the server. Supposedly this has been down for at least 2 days as of this report.

**Comment by hafarooki** [comment]
please fill out the form including reproduction steps and screenshots

**Comment by CodingIsAHabit** [comment]
Issue resolved
