### ISSUE TITLE
Chetherite in bazaar identifies as "Iron Ingot" in bazaar list[BUG]

### ISSUE THREAD

**Issue by Mr-CleanCreeper** [StarLegacy/Issue-Tracker#258]
**Describe the bug**

When selling chetherite on the bazaar it shows as "Iron ingot" in the list but you can deposit and withdraw with "chetherite" string. 
**To Reproduce**

Sell chetherite on the bazaar
**Expected behavior**

Should be named "Chetherite" in bazaar list instead of "Iron Ingot'
**Screenshots**

**System (please complete the following information):**

- OS: [e.g. Windows]
- RAM: [e.g. 8gb RAM]
- Minecraft Version: [e.g. Minecraft Java Edition 1.16.3]
Windows 10
32Gb
1.16.3
**Additional context**

A regular iron ingot is listed under the same name creating confusion.

**Comment by zelrond** [comment]
Related to this: titanium is also being recognized as IRON for recipes, so power armor is not craftable right now! It seems that's not happening with copper, since you can craft wires!

**Comment by hafarooki** [comment]
that is a separate issue, zelrond

**Comment by zelrond** [comment]
Ok got it, will load it to the tracker in another issue then!

**Comment by hafarooki** [comment]
this should be fixed
