### ISSUE TITLE
Wet Sponges do not transfer power[BUG]

### ISSUE THREAD

**Issue by Mr-CleanCreeper** [StarLegacy/Issue-Tracker#259]
**Describe the bug**

A regular sponge will still transfer power but when the sponge becomes wet it will no longer transfer power.
**To Reproduce**

Place a wet sponge in a power grid
**Expected behavior**

Wet sponges used to transfer power exactly the same as regular sponges.
**Screenshots**

**System (please complete the following information):**

- OS: [e.g. Windows]
- RAM: [e.g. 8gb RAM]
- Minecraft Version: [e.g. Minecraft Java Edition 1.16.3]
Windows 10
32Gb
1.16.3
**Additional context**

This glitch makes power transfer much more difficult if your gridlines are near water.

**Comment by hafarooki** [comment]
this isnt really an issue, if anything, the fact that it worked before is a bug. perhaps a new more expensive waterproof block could be used for underwater wires

**Comment by Mr-CleanCreeper** [comment]
That sounds like a cool idea. Possibly a custom crafted block that is made with honey as insulation.

**Comment by CodingIsAHabit** [comment]
Resolved
