### ISSUE TITLE
[BUG] Power armor isn't craftable

### ISSUE THREAD

**Issue by zelrond** [StarLegacy/Issue-Tracker#260]
**Describe the bug**
Power armor isn't craftable since titanium is being recognized as iron (or there is an issue with the battery maybe?)

**To Reproduce**
- try to craft a power armor chestplate
- nothing comes out

**Expected behavior**
- try to craft a power armor chestplate
- power armor chestplate available

**System (please complete the following information):**
Windows 10. MC 1.16.3

**Comment by Maxbrick** [comment]
I just tried it and it works. Most likely you used a size G battery that didnt have 2000 power (which is required.)

**Comment by Maxbrick** [comment]
If it still doesn't work, show a screenshot
