### ISSUE TITLE
Inverted Solar Panels no longer function.[BUG]

### ISSUE THREAD

**Issue by Mr-CleanCreeper** [StarLegacy/Issue-Tracker#262]
**Describe the bug**

Inverted solar panels no longer produce power at night but instead produce power during the day as regular panels do.
**To Reproduce**

Build a solar panel and invert the daylight sensor to detect night
**Expected behavior**

When a daylight sensor is inverted on a solar panel the solar panel is expected to produce power during night time. 

**Screenshots**

![2020-10-30_09 56 46](https://user-images.githubusercontent.com/73080390/97720544-65c8b100-1a96-11eb-84fc-a77cdc7520d6.png)

**System (please complete the following information):**

- OS: [e.g. Windows]
- RAM: [e.g. 8gb RAM]
- Minecraft Version: [e.g. Minecraft Java Edition 1.16.3]
Windows 10
32Gb
1.16.3
**Additional context**

I personally think this should become a mechanic because real solar panels dont produce power at nighttime and planets with long nights will force people to use other power production options.

**Comment by hafarooki** [comment]
If they ever produced power at night (I doubt it), it was a bug. They're supposed to only produce power in the day.
