### ISSUE TITLE
[BUG] Minecraft PE crashing while loading commands

### ISSUE THREAD

**Issue by misdamer3** [StarLegacy/Issue-Tracker#268]
**Describe the bug**

After loading the app and joining the server, often times after opening chat and typing in “ / “ the game will freeze and crash. This is due to, I believe, the game trying to load all available commands and timing out, but may not be. It causes both the server (on users end) and game/app to crash

**To Reproduce**

1. Open Minecraft PE on iPhone
2. Join SL
3. Open chat
4. Type in “ / “
5. Wait. It will take forever to load, and then will randomly crash. Not 100% of the time, but often enough to not be a random occurrence

**Expected behavior**

Instead of crashing the game, it should have let me type in the rest of the desired command after the backslash “ / “

**Screenshots**

Nothing visual to report

**System (please complete the following information):**

- OS: iOS 14.1
- RAM: 3 gb
- Minecraft Version: Minecraft Pocket Edition (Bedrock) 1.16.40 

**Additional context**

For Minecraft PE (Bedrock) for iPhone

**Comment by Maxbrick** [comment]
Hmm, this used to happen to me as well. It seems to happen because on Bedrock Edition, when you type "/" in chat, it loads _every command_ in star legacy. I don't think there would be a way to fix that, besides removing the commands, so that would mostly be a bug on GeyserMC, not Star Legacy.

**Comment by Maxbrick** [comment]
If you want your own fix, type in the command first, then put / at the beginning of the text (e.g. typer server creative, then put a / behind the word server when you are done typing it. this way it won't load all the commands

**Comment by tallboi** [comment]
Good idea, I will give that a shot. Thank you

**Comment by misdamer3** [comment]
Good idea, I will give that a shot. Thank you

**Comment by Maxbrick** [comment]
Since this is a geyserMC problem and not an SL problem, I closed the issue
