### ISSUE TITLE
Command /ecostations did not generate worldguard [BUG]

### ISSUE THREAD

**Issue by zelrond** [StarLegacy/Issue-Tracker#270]
**Describe the bug**
/ecostation create cordis_station 100000 110000
It didn't give the station worldguard, with it resulting in griefing and an adminclaim having to be created

**To Reproduce**
/ecostation create stationname coordx coordz
bring any survival player not OP to the place
making him break stuff
stuff breaks

**Expected behavior**
Stuff not to break

**System (please complete the following information):**
Win10 and MC 1.16.3

**Additional context**
Old stations work fine, their wolrdguard is still up

**Comment by hafarooki** [comment]
It's not supposed to, make the worldguard manually (and don't use admin claims)
