### ISSUE TITLE
[BUG] Mining Modules Don't Collect All Mats When Deconstructing A Ship

### ISSUE THREAD

**Issue by WatchmanPhileo** [StarLegacy/Issue-Tracker#278]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**System (please complete the following information):**
- Minecraft Version: [e.g. Minecraft Java Edition 1.16.3]

**Comment by CodingIsAHabit** [comment]
Please fill out the form in its entirety. This doesn't give us much to work on.
