### ISSUE TITLE
[BUG] Fall damage is re-implemented

### ISSUE THREAD

**Issue by kwazedilla** [StarLegacy/Issue-Tracker#281]
**Describe the bug**

Fall damage on the Star Legacy survival server has been re-implemented, allowing players to take normal fall damage in Minecraft. Fall damage was not present for a better part of a year and interferes with core game mechanics such as double jump and rocket boots.

**To Reproduce**

- Be in survival mode.
- Be at a height of 4 or more blocks from the ground.
- Descend to a lower height, whether it be from falling or rocket boots.
- The player will take fall damage.

**Expected behavior**

Fall damage should not exist, as it has been disabled for the better part of a year (at least).

**System (please complete the following information):**

- OS: Windows
- RAM: 8gb RAM
- Minecraft Version: Minecraft Java Edition 1.16.3

**Additional context**

kwaze watches

**Comment by zelrond** [comment]
Solved!
