### ISSUE TITLE
[BUG] Chests spew items out when blown up 

### ISSUE THREAD

**Issue by Wither7000** [StarLegacy/Issue-Tracker#283]
**Describe the bug**

Any type of explosion causes the contents of a container to spill out. Usually the chest just blows up without the items spilling out. This was not the case before Land Legacy was introduced. 
**To Reproduce**

Take either a blaster cannon, thermal detonator or spaceship and blow up the container that contains items. Works on both the survival and creative server.
**Expected behavior**

Containers are supposed to retain their items when blown up. 
**Screenshots**

![image](https://user-images.githubusercontent.com/74421145/99149021-c0affa00-268b-11eb-8caa-868e5e592a86.png)
![image](https://user-images.githubusercontent.com/74421145/99149033-d1607000-268b-11eb-9737-cb933ee56d33.png)

**Additional context**

My friend accidentally threw a detonator at one of our chests when attempting to open it. This made the contents of the chest spill out, we were confused since whenever that happened the chest would usually just blow up and regenerate without the items being thrown out. 

**System (please complete the following information):**

- OS: Windows
- RAM: 8gb RAM
- Minecraft Version: Minecraft Java Edition 1.16.3

**Comment by CodingIsAHabit** [comment]
Resolved ages ago
