### ISSUE TITLE
Gas canister recipe not working [BUG]

### ISSUE THREAD

**Issue by zelrond** [StarLegacy/Issue-Tracker#289]
**Describe the bug**
Gascanister recipe doesnt work

**To Reproduce**
- Load the recipe for gas cannister in a crafting table
- Nothing happens

**Expected behavior**
Gascannisters to be crafted

**System (please complete the following information):**
Win 10
MC 1.16.4

**Comment by hafarooki** [comment]
use titanium not iron nuggets
