### ISSUE TITLE
[BUG] mesh shields broken

### ISSUE THREAD

**Issue by SciathGH** [StarLegacy/Issue-Tracker#293]
**Describe the bug**

Me and jeff were testing mesh shields when we noticed I would say a big bug. when u hit a mesh shields inside, we used 7 7 7 btw the shield takes damage however if u hit it from the outside the blocks get destroyed, note the blocks were 6 blocks away from the sign.
**To Reproduce**

Shoot a box I guess from inside and outside
**Expected behavior**

shield should take damage instead of block damage on inside
**Screenshots**

![2020-11-26_22 18 44](https://user-images.githubusercontent.com/67932943/100394741-25793600-3036-11eb-9dae-9137c45100d4.png)
![2020-11-26_22 18 52](https://user-images.githubusercontent.com/67932943/100394745-290cbd00-3036-11eb-9389-90f115012ca4.png)

**System (please complete the following information):**

- OS: [e.g. Windows] windows
- RAM: [e.g. 8gb RAM] 8gb
- Minecraft Version: [e.g. Minecraft Java Edition 1.16.3] java 1.16.3

**Additional context**

**Comment by hafarooki** [comment]
this entire class of bugs should be eliminated as of a change i just made that should be effective next restart
