### ISSUE TITLE
Schem folder path incorrect for survival (or creative, just pic one!)[BUG]

### ISSUE THREAD

**Issue by zelrond** [StarLegacy/Issue-Tracker#294]
**Describe the bug**
Schem folder in survival is changed, it isn't the same as in creative

**To Reproduce**
Do /schem list in creative and then in survival
Completely different lists

**Expected behavior**
Same lists, so we can load the new server builds in survival

**System (please complete the following information):**
win 10 and MC 1.16.4

**Comment by hafarooki** [comment]
You will need to `//schem save ../path.schem` on creative for it to work. This is because creative uses FAWE, which uses per world schematics, while survival used regular worldedit, which does not.
