### ISSUE TITLE
Custom recipes stopped working (again) [BUG]

### ISSUE THREAD

**Issue by zelrond** [StarLegacy/Issue-Tracker#295]
**Describe the bug**
Custom recipes dont work anymore again, something was touched there. Power armor, gas canisters, etc.

**To Reproduce**
Try to craft a gas canister, or power armor. Nothing comes out.

**Expected behavior**
custom recipes to work

**Screenshots**
![image](https://user-images.githubusercontent.com/58335728/100514253-da544580-3151-11eb-8678-2b0bc923d82e.png)

**System (please complete the following information):**
win 10 and mc 1.16.4

**Comment by hafarooki** [comment]
it appears that the issue is that you are using iron nuggets instead of titanium or something
