### ISSUE TITLE
[BUG] /dye cant dye light gray to black.

### ISSUE THREAD

**Issue by Astralchroma** [StarLegacy/Issue-Tracker#298]
**Describe the bug**

When trying to /dye black while holding light gray glass it says "Error: Item material LIGHT_BLACK_STAINED_GLASS doesn't exist"

**To Reproduce**

Run /dye while holding light gray glass.

**Expected behavior**

The glass becomes the colour specified.

**Comment by Astralchroma** [comment]
The issue also exists with glass panes, it is likely it exists with concrete and terracotta.

**Comment by Astralchroma** [comment]
Just checked, same issue with concrete too

**Comment by Emeris4017** [comment]
This has been fixed for a while, dunno why it isn't closed.
