### ISSUE TITLE
[BUG] chetherite block -> chetherite recipe is missing

### ISSUE THREAD

**Issue by SciathGH** [StarLegacy/Issue-Tracker#310]
**Describe the bug**

If u try craft chetherite blocks back into chetherite it instead turns to iron
**To Reproduce**

Grab a chetherite block and put it in a crafting table
**Expected behavior**

Should turn into  chetherite
**Screenshots**

![2021-01-09_15 47 59](https://user-images.githubusercontent.com/67932943/104098956-97c77200-5294-11eb-90a0-5223f720eccf.png)

**System (please complete the following information):**

- OS: [e.g. Windows] windows
- RAM: [e.g. 8gb RAM] 8gb
- Minecraft Version: [e.g. Minecraft Java Edition 1.16.3] java 1.16.4

**Additional context**

I tested Titanium and uranium and their recipes were fine

**Comment by CodingIsAHabit** [comment]
Issue resolved, case of faulty chetherite blocks, ask for a refund
